bump_version: null
lint:
  files_unchanged:
    - assets/email_template.html
    - assets/email_template.txt
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Chris Cheshire, Charlotte West and Tamara Hodgetts
  description: Analysis pipeline for CUT&RUN and CUT&TAG experiments that includes
    sequencing QC, spike-in normalisation, IgG control normalisation, peak calling
    and downstream peak analysis.
  force: false
  is_nfcore: true
  name: cutandrun
  org: nf-core
  outdir: .
  skip_features: null
  version: 3.2.2
update: null
